# Generated by Django 4.2 on 2023-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_members_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='status',
            field=models.CharField(choices=[('AMB', 'ACTIVE_MEMBER'), ('INMB', 'INACTIVE_MEMBER')], default='INMB', max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('FSHD', 'FINISHED'), ('UFSHD', 'UNFINISHED')], default='UFSHD', max_length=30),
        ),
    ]
