# Generated by Django 4.2 on 2023-08-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_members_status_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='git_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='insta_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='port_link',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='members',
            name='tg_link',
            field=models.URLField(max_length=100),
        ),
    ]
