# Generated by Django 4.2 on 2023-08-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_members_slug_post_slug_alter_members_git_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='git_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='insta_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='port_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='tg_link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
