# Generated by Django 4.2 on 2023-08-19 15:21

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_members_git_link_alter_members_insta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='images/members'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='images/post'),
        ),
    ]
